jobs:
    perl:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                perl-version:
                    - '5.14'
                    - 'latest'
                    - 'threaded'

        container:
            image: perl:${{ matrix.perl-version }}

        steps:
            - uses: actions/checkout@v2
            - name: perl -V
              run: perl -V
'on':
    - push
